### ISSUE TITLE
大佬 v2可以设置像V1那样无就是无吗

### ISSUE THREAD

**Issue by lhj5426** [hiroi-sora/Umi-OCR_v2#1]
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/30548000/63e94c43-806b-4d6d-9ae5-f5032c7170cf)
大佬你好 试了下 v2 发现个小改动很不舒服
就是 这个输出无的时候 还能按照原来的 无输出么 
为什么呢
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/30548000/950830bc-b92a-460e-bd42-b7293bb1ba58)
我是用来 处理硬字幕 扫空图的
V1的时候全扫一遍之后 用按大小排序分组的方式
因为V1扫空可以直接生成一个0K的文档 这样通过 按文件大小分组 可以 快速筛选出 来没有字幕的图
而且软件有个功能 可以 左右 互相选择同名且不限制后缀的 相同文件名的文件
这样我可以用 右侧的 扫除来的 空字节文档 一键反选 左边的 同名 图片
这样 就把 空字幕的图片筛选出来了
而今天用了下V2 
V2这个改动 无不再是生成一个0K的文档 而是多了一段提示 导致 不是0K 无法通过 按大小排序 进行确认了
无法筛选出来图片了 哈哈
所以 就来发个 议题 来说一下
这个改动 可以 设置一下还是 生成0K的文档吗

实际上这个 0K 的文档 比 写温馨提示 更具有作用

**Comment by hiroi-sora** [comment]
感谢提醒，你说得有道理，确实可能原来更好。我后续会改回来。

目前，你可以通过下列操作恢复原来的空输出：

1. 打开 `软件目录/UmiOCR-data/pyapp/ocr/output`
2. 用记事本打开 `output_txt_individual.py`
3. 找到第18行，将原文：
`            textOut += "[Notice] No Text. \n【通知】图片中未找到文字。\n"`
    改为：
`            textOut += ""`
    注意不要改变语句前的空格数量。
4. 重新启动Umi-OCR，测试效果。

**Comment by lhj5426** [comment]
> 感谢提醒，你说得有道理，确实可能原来更好。我后续会改回来。
> 
> 目前，你可以通过下列操作恢复原来的空输出：
> 
> 1. 打开 `软件目录/UmiOCR-data/pyapp/ocr/output`
> 2. 用记事本打开 `output_txt_individual.py`
> 3. 找到第18行，将原文：
>    `            textOut += "[Notice] No Text. \n【通知】图片中未找到文字。\n"`
>    改为：
>    `            textOut += ""`
>    注意不要改变语句前的空格数量。
> 4. 重新启动Umi-OCR，测试效果。

感谢大佬 我去按照您说的试试

**Comment by lhj5426** [comment]
> 感谢提醒，你说得有道理，确实可能原来更好。我后续会改回来。
> 
> 目前，你可以通过下列操作恢复原来的空输出：
> 
> 1. 打开 `软件目录/UmiOCR-data/pyapp/ocr/output`
> 2. 用记事本打开 `output_txt_individual.py`
> 3. 找到第18行，将原文：
>    `            textOut += "[Notice] No Text. \n【通知】图片中未找到文字。\n"`
>    改为：
>    `            textOut += ""`
>    注意不要改变语句前的空格数量。
> 4. 重新启动Umi-OCR，测试效果。

大佬还有个问题
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/30548000/640c3d22-ed3d-4ef2-a7ca-4ddf09cc8d7f)

识别完 是 原始文件名.原始扩展.txt

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/30548000/901b1a83-8718-4dd0-a8f7-3631b9fb9b0e)
我xi修改了这里的扩展 变成 了
左边的这个样子 
能不能 识别结果是 
原始文件名.txt
而不是
原始文件名.原始扩展.txt

**Comment by hiroi-sora** [comment]
当然可以，用python先去除原本的后缀（如`.png`），然后加上自己的后缀（`.txt`）即可。

在文件开头加上：
```python
import os
```

将原本的`path = res["path"] + ".txt"` 去掉，换成：
```python
        path, extension = os.path.splitext(res["path"])  # 截取不含后缀的内容
        path = path + ".txt"  # 加上新的后缀
```

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/63ac3f15-d8fc-4cdd-8407-f3c0815efb14)
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/092c7c6c-6b1e-49df-85ab-a4ee7a9cf6e6)

**Comment by lhj5426** [comment]
> 当然可以，先去除原本的后缀（如`.png`），然后加上自己的后缀（`.txt`）即可。
> 
> 在文件开头加上：
> 
> ```python
> import os
> ```
> 
> 将原本的`path = res["path"] + ".txt"` 去掉，换成：
> 
> ```python
>         path, extension = os.path.splitext(res["path"])  # 截取不含后缀的内容
>         path = path + ".txt"  # 加上新的后缀
> ```
> 
> ![image](https://user-images.githubusercontent.com/56373419/268216673-63ac3f15-d8fc-4cdd-8407-f3c0815efb14.png) ![image](https://user-images.githubusercontent.com/56373419/268216832-092c7c6c-6b1e-49df-85ab-a4ee7a9cf6e6.png)

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/30548000/ac5eee41-fccb-416b-9a57-1c5352552b7c)
大佬现在 按您给的这么写之后  运行不会生成TXT了

**Comment by hiroi-sora** [comment]
哈哈哈哈，典中典之空格位数不对 🤣

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/7f63fe08-9624-4881-96cf-7a69f394b90a)

多了四个空格。这两行应该跟下面的with对齐。

**Comment by lhj5426** [comment]
> 哈哈哈哈，典中典之空格位数不对 🤣
> 
> ![image](https://user-images.githubusercontent.com/56373419/268239041-7f63fe08-9624-4881-96cf-7a69f394b90a.png)
> 
> 多了四个空格。这两行应该跟下面的with对齐。

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/30548000/6807b616-7a7a-4b29-a98b-d2dddf375fa3)
还真是  空格 的锅 谢谢大佬 了

**Comment by lhj5426** [comment]
> > 哈哈哈哈，典中典之空格位数不对 🤣
> > ![image](https://user-images.githubusercontent.com/56373419/268239041-7f63fe08-9624-4881-96cf-7a69f394b90a.png)
> > 多了四个空格。这两行应该跟下面的with对齐。
> 
> ![image](https://user-images.githubusercontent.com/30548000/268272065-6807b616-7a7a-4b29-a98b-d2dddf375fa3.png) 还真是 空格 的锅 谢谢大佬 了

这样就可以用同名文件名 忽略扩展名 搜到到了 非常感谢
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/30548000/747a893c-fef1-44b6-b8e0-c20b19b1a838)
