### ISSUE TITLE
关于通知弹窗的建议

### ISSUE THREAD

**Issue by JerManh** [hiroi-sora/Umi-OCR_v2#10]
1. 通知弹窗类型->只允许外部：在关闭了识图完成后的操作->弹出主窗口，能否增加功能——通过双击通知弹窗，跳出主窗口，这样可以选择性的进行文本比对修改，不用每次都要打开再关闭窗体或是手动打开主窗体比对。（或者另设置快捷键弹出主窗体，比如双击Ctrl键弹出主窗体）
2. [通知弹窗类型->跟随全局设定/只允许内部：建议通知弹窗的显示位置可以调整一下在图片的显示区，这样不会挡到识别记录，尤其最新识别记录较短，会短暂被遮挡。
3. 不得不夸一下作者，这个版本的UI设计很awesome！
4. 识别记录建议增加一个批量删除的选项或者识别记录单体删除，这样选择性保留目标文本，方便寻找，如果后期退出记录保存的话，也能协同该功能进行记录管理。
5. 关于界面和外观问题：黑暗主题的窗体顶部还是白色的，要是也是很黑色就更好了。
  以上这些是我体验尝鲜的一些小建议，第一次提，没什么经验，提出的建议如有不当，请忽略或者指正。最后不得不提，对比V1.3版本，整体设计真的很好。
![Snipaste_2023-09-29_10-24-41](https://github.com/hiroi-sora/Umi-OCR_v2/assets/141105978/fbc12ea2-a163-47f6-b014-c4710dd8e687)

**Comment by hiroi-sora** [comment]
OK，感谢反馈和支持~

1. 双击弹窗或快捷键打开主窗口，很不错的建议。
2. 截图OCR完成后，通知遮挡的问题。我想如果主窗口在前台，那干脆不弹完成通知得了。
4. 关于删除指定记录 和 历史记录功能，其实是有一定技术困难和很大工作量，暂时不想搞😂
5. 窗口顶部标题栏属于系统控制范围，软件无法调整。当然我也想过设为无边框窗口，自己绘制标题栏；不过有一定技术困难和巨大的工作量。接口我都预留好了，以后有空慢慢实现吧

**Comment by JerManh** [comment]
哈哈，慢慢来啦，希望越做越好，顺祝中秋国庆快乐！

**Comment by hiroi-sora** [comment]
#### 加了这个功能，左键选中多个文本框 → 右键 → 删除。

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/92778a33-437b-4d25-8e5f-3cdc3ad11162)
