### ISSUE TITLE
截图高亮效果bug

### ISSUE THREAD

**Issue by LanRenLan** [hiroi-sora/Umi-OCR_v2#11]
下图是拿手机拍的，因为电脑截图看不出问题。
当时软件在后台运行有一段时间了，后来按截图识别的快捷键的时候，软件立刻闪退了，然后就导致只有一个浏览器的窗口的亮度是正常的以外，其他窗口全都是低亮度。我手动杀了引擎和软件也不好使，我重新开关HDR解决了。软件版本是20230925
![485abc824255ba9c2013e73327ee3d0](https://github.com/hiroi-sora/Umi-OCR_v2/assets/112599739/6e2c2e5e-7aa9-4837-9d3f-bf43ac9c1dc8)

**Comment by hiroi-sora** [comment]
啊，这就有点奇怪。我的截图高亮效果，实际上是创建了一个无边框窗口，在该窗口上绘制图案、降低亮度。它不可能导致别的窗口颜色改变，也不可能影响到win+tab的系统界面。跟HDR应该也没啥联系。

如果你后续还有复现类似问题，请继续跟我说，提供更多线索。

**Comment by LanRenLan** [comment]
当时不仅仅是win tab的界面低亮度，其他所有窗口 正常使用的时候亮度都会特别低，以后有出现的话再来，谢谢

hiroi-sora ***@***.***> 于2023年10月4日周三 03:41写道：

**Comment by LanRenLan** [comment]
又有了，是Desktop OpenGL的问题，用OpenGL ES的时候没有问题。还是截图之后会亮度变得很低。没有找到什么共同点，可能是开着HDR吧
