### ISSUE TITLE
有个图片的出厂编号识别不出，但是截图可以识别，不知道是不是设置的问题？

### ISSUE THREAD

**Issue by honghong82** [hiroi-sora/Umi-OCR_v2#12]
正好手里有一张照片，里面的出厂编号识别不出来，文字识别比较快，截图之后可以识别。不知道是不是设置的问题，谢谢。
![230297](https://github.com/hiroi-sora/Umi-OCR_v2/assets/806491/950cb3a9-af80-4246-831c-bdbd5f076f2a)

**Comment by hiroi-sora** [comment]
出厂编号这几个字相对不明显，轻量级识别库确实不容易认得出。如果有识别这种图片的需求的话，用高精度识别库的准确度会好很多。

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/49d2f907-d33a-4741-8393-c50eec3a4fac)

不过高精度库的体积很大，近200MB。识别速度也很慢，可能一张图要30s以上；我觉得日常实用 不太实用。你有需要的话，我传给你。

**Comment by honghong82** [comment]
谢谢，如果有高精度库，请发一份给我。










在 2023-10-04 19:17:21，"hiroi-sora" ***@***.***> 写道：

出厂编号这几个字相对不明显，轻量级识别库确实不容易认得出。如果有识别这种图片的需求的话，用高精度识别库的准确度会好很多。

不过高精度库的体积很大，近200MB。识别速度也很慢，可能一张图要30s以上；我觉得日常实用 不太实用。你有需要的话，我传给你。

**Comment by hiroi-sora** [comment]
高精度库的整合包要200M，github及蓝奏云传不了。我只能把每个组件的链接给你，请按下列步骤组装：

1. 下载两个组件
[ch_PP-OCRv4_det_server_infer](https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_server_infer.tar)
[ch_PP-OCRv4_rec_server_infer](https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_rec_server_infer.tar)

2. 将其解压到软件目录的 `\UmiOCR-data\lib\PaddleOCR-json\models` 。
3. 在上述目录，添加一个文件 `config_chinese_v4_server.txt` ，粘贴以下文本：
```
# 简中 PP-OCR v4

det_model_dir models/ch_PP-OCRv4_det_server_infer
cls_model_dir models/ch_ppocr_mobile_v2.0_cls_infer
rec_model_dir models/ch_PP-OCRv4_rec_server_infer
rec_char_dict_path models/dict_chinese.txt
```
4. 打开 `configs.txt` ，添加一行文本（不要删除其它内容）：
```
config_chinese_v4_server.txt 简体中文(高精度)
```
5. 完成，打开Umi-OCR，模型库下拉框中选择 `简体中文(高精度)`

**Comment by hiroi-sora** [comment]
顺便把Rapid版的方法也说了：

## 适用于Rapid引擎的，高精度中文识别库下载 / 导入方法

（链接来源于[RapidAI](https://github.com/RapidAI)官方）

1. https://pan.baidu.com/s/1PTcgXG2zEgQU6A_A3kGJ3Q?pwd=jhai
打开目录 `全部文件 > RapidOCR >PP-OCRv4` ，下载这两个文件：
ch_PP-OCRv4_det_server_infer.onnx
ch_PP-OCRv4_rec_server_infer.onnx

2. 将放置到软件目录的 `\UmiOCR-data\lib\RapidOCR-json\models` 。
3. 打开 `configs.txt` ，添加下列文本（不要删除其它内容）：
```
简体中文(V4 高精度)
ch_PP-OCRv4_det_server_infer.onnx
ch_ppocr_mobile_v2.0_cls_infer.onnx
ch_PP-OCRv4_rec_server_infer.onnx
dict_chinese.txt
```
5. 完成，打开Umi-OCR，模型库下拉框中选择 `简体中文(V4 高精度)`

**Comment by nissansz** [comment]
> 高精度库的整合包要200M，github及蓝奏云传不了。我只能把每个组件的链接分开给你，请按下列步骤组装：
> 
> ## 适用于Paddle引擎的，高精度中文识别库下载 / 导入方法
> （下载链接来源于[Paddle官方](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/models_list.md)）
> 
> 1. 下载两个组件
>    [ch_PP-OCRv4_det_server_infer](https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_server_infer.tar)
>    [ch_PP-OCRv4_rec_server_infer](https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_rec_server_infer.tar)
> 2. 将其解压到软件目录的 `\UmiOCR-data\lib\PaddleOCR-json\models` 。
> 3. 在上述目录，添加一个文件 `config_chinese_v4_server.txt` ，粘贴以下文本：
> 
> ```
> # 简中 PP-OCR v4
> 
> det_model_dir models/ch_PP-OCRv4_det_server_infer
> cls_model_dir models/ch_ppocr_mobile_v2.0_cls_infer
> rec_model_dir models/ch_PP-OCRv4_rec_server_infer
> rec_char_dict_path models/dict_chinese.txt
> ```
> 
> 4. 打开 `configs.txt` ，添加一行文本（不要删除其它内容）：
> 
> ```
> config_chinese_v4_server.txt 简体中文(高精度)
> ```
> 
> 5. 完成，打开Umi-OCR，模型库下拉框中选择 `简体中文(高精度)`

rec模型字典文件在哪里设置？

**Comment by hiroi-sora** [comment]
> rec模型字典文件在哪里设置？

这一行：
rec_char_dict_path models/dict_chinese.txt

**Comment by Nicolas-One** [comment]
> 高精度库的整合包要200M，github及蓝奏云传不了。我只能把每个组件的链接分开给你，请按下列步骤组装：
> 
> ## 适用于Paddle引擎的，高精度中文识别库下载 / 导入方法
> （下载链接来源于[Paddle官方](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/models_list.md)）
> 
> 1. 下载两个组件
>    [ch_PP-OCRv4_det_server_infer](https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_server_infer.tar)
>    [ch_PP-OCRv4_rec_server_infer](https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_rec_server_infer.tar)
> 2. 将其解压到软件目录的 `\UmiOCR-data\lib\PaddleOCR-json\models` 。
> 3. 在上述目录，添加一个文件 `config_chinese_v4_server.txt` ，粘贴以下文本：
> 
> ```
> # 简中 PP-OCR v4
> 
> det_model_dir models/ch_PP-OCRv4_det_server_infer
> cls_model_dir models/ch_ppocr_mobile_v2.0_cls_infer
> rec_model_dir models/ch_PP-OCRv4_rec_server_infer
> rec_char_dict_path models/dict_chinese.txt
> ```
> 
> 4. 打开 `configs.txt` ，添加一行文本（不要删除其它内容）：
> 
> ```
> config_chinese_v4_server.txt 简体中文(高精度)
> ```
> 
> 5. 完成，打开Umi-OCR，模型库下拉框中选择 `简体中文(高精度)`




根据这个方式增加了config_en_v4.txt配置文件，发现识别结果里全是乱码，不知道为什么，我下载文件有
```
ch_PP-OCRv4_det_infer
ch_PP-OCRv4_det_server_infer
en_PP-OCRv4_rec_infer
```

```
# 纯英文 PP-OCR v4

# det 检测模型库
det_model_dir models/ch_PP-OCRv4_det_infer

# cls 方向分类器库
cls_model_dir models/ch_ppocr_mobile_v2.0_cls_infer

# rec 识别模型库
rec_model_dir models/en_PP-OCRv4_rec_infer

# 字典路径
rec_char_dict_path models/dict_en.txt
```
`det_model_dir models/ch_PP-OCRv4_det_infer` 这里不管是使用`ch_PP-OCRv4_det_server_infer`还是`ch_PP-OCRv4_det_infer`都是乱码
返回的结果是：
```
[
    {
        "box": [
            [
                1081,
                313
            ],
            [
                1450,
                313
            ],
            [
                1450,
                336
            ],
            [
                1081,
                336
            ]
        ],
        "score": 1,
        "text": "                ",
        "end": " "
    },
    {
        "box": [
            [
                1070,
                345
            ],
            [
                1458,
                344
            ],
            [
                1458,
                368
            ],
            [
                1070,
                369
            ]
        ],
        "score": 1,
        "text": "  a        :",
        "end": " "
    }
]    
```
坐标系都是正确的，但是text内文字内容是乱码，另外所有的置信度都一直是1
