### ISSUE TITLE
有单字识别高精度模型吗？

### ISSUE THREAD

**Issue by nissansz** [hiroi-sora/Umi-OCR_v2#13]
有单字识别高精度模型吗？

**Comment by hiroi-sora** [comment]
“单字识别”是没有的，引擎的解析结果就是以文本块（行）为单位。

如需高精度库请见：
https://github.com/hiroi-sora/Umi-OCR_v2/issues/12

**Comment by nissansz** [comment]
谢谢。ppstructure的模型，你会转onnx吗？

**Comment by nissansz** [comment]
谢谢。ppstructure的模型，你会转onnx吗？
