### ISSUE TITLE
关于通知弹窗遇到的问题及建议

### ISSUE THREAD

**Issue by hihvan** [hiroi-sora/Umi-OCR_v2#14]
## 外部弹窗阴影变成了黑色方块。

- 在内部是正常的
- 渲染器选择 关闭硬件加速、DesktopOpenGl 、以及选择禁用美化效果都会这样，OpenGLES 开启会无法使用，只能重新解压，可能是我这个电脑太老的原因。

> ![截图_20231006_105717](https://github.com/hiroi-sora/Umi-OCR_v2/assets/122767273/6b5f8389-a3c4-423d-a69a-9f4326fa6147)

## 建议弹窗跟随鼠标所在屏幕显示
- 我有使用2个屏幕，使用过程中发现，弹窗提示只会在主屏幕显示。
-  如果根据鼠标当前所在屏幕进行显示，可能会有更好的使用感受

**Comment by hiroi-sora** [comment]
是的，这个弹窗的周围是一层半透明阴影。我在显卡驱动不全的早期win7系统测试，也复现了同样问题。显卡无法渲染半透明区域，所以变成了全黑。

我之后会改善这个问题，至少让禁用美化效果时能够关闭这片半透明区域。感谢建议。
