### ISSUE TITLE
识别率很高，但是不支持空格，会导致英文ocr识别存在问题

### ISSUE THREAD

**Issue by 94zuocom** [hiroi-sora/Umi-OCR_v2#15]
问题如图，第三段是没有空格区分单词的
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/19161243/dda935ea-076d-4da3-a2f1-c15852c33443)

**Comment by 94zuocom** [comment]
操作系统是windows11 版本：Umi-OCRv2.0.0-dev.20230925

**Comment by hiroi-sora** [comment]
这也是老问题了，用简中库识别英文段落就容易丢失空格。

识别长篇英文段落，请切换到 English 识别库。能有效识别空格。
