### ISSUE TITLE
使用截图ocr，在副屏截图后，副屏会变成全黑，退出软件后恢复正常

### ISSUE THREAD

**Issue by moyushang** [hiroi-sora/Umi-OCR_v2#16]

**Comment by hiroi-sora** [comment]
反馈收到。请问一下：
- win7还是win10/11？
- 是截图完成之后，副屏变黑吗？还是截图一开始，就不正常？
- 每次截图都会出现该问题吗？
- 你的显卡是什么（核显 / N卡 / A卡？）
- 出现该故障时，除了副屏变黑以外，软件本身能否继续使用（还是卡死了）？

**Comment by moyushang** [comment]
> 反馈收到。请问一下：
> 
> * 是截图**完成后**，副屏变黑吗？还是截图一开始，不正常？
> * 打开软件截图会出现该问题吗？
> * 出现该故障时，除了副屏变黑以外，软件本身能否继续使用（还是卡死了）？
> * win7还是win10/11？
> * 你的显卡是什么（核显/N卡/A卡？）

截图完成后，主屏和副屏闪了下，副屏变黑，主屏正常显示。

**Comment by hiroi-sora** [comment]
嗯，感觉可能是渲染问题。

请尝试在全局设置里，渲染器调成 `Opengl ES` 或者 `关闭硬件加速` 。

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/e76ba5bd-808b-47f0-a18b-001c7aaa3d70)

**Comment by moyushang** [comment]
> Opengl ES

更换Opengl ES后问题解决了
