### ISSUE TITLE
V1截图几张之后，统一复制文字，自己再格式化。现在每个图识别结果是分开的，无法全选复制

### ISSUE THREAD

**Issue by plumhua** [hiroi-sora/Umi-OCR_v2#18]
新版识别很准确，也很快速，但是多图截图识别后，每个图片的结果在记录里面是分开的，无法全选复制，

**Comment by hiroi-sora** [comment]
嗯，建议收到。后续我会看看能不能实现跨对话框框选文字，或者多加一个类似v1的整体文本框界面。

**Comment by hiroi-sora** [comment]
### 基本实现了一套跨文本框选取和复制的机制

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/19aba51c-f63c-4a51-a8d5-7d62c577ca97)
