### ISSUE TITLE
希望增加一个显示图片的窗体，方便跟识别后的文本进行人工校对

### ISSUE THREAD

**Issue by wyhsz** [hiroi-sora/Umi-OCR_v2#2]
希望增加一个显示图片的窗体，方便跟识别后的文本进行人工校对

**Comment by hiroi-sora** [comment]
批量识别模式吗？

**Comment by wyhsz** [comment]
是的，每点一个文件路径时，可以显示识别的内容和原图片，人工就很方便进行校对了。



王燕辉
***@***.***







                       
Original Email
                       
                     

Sender:"hiroi-sora"< ***@***.*** &gt;;

Sent Time:2023/9/15 11:41

To:"hiroi-sora/Umi-OCR_v2"< ***@***.*** &gt;;

Cc recipient:"wyhsz"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [hiroi-sora/Umi-OCR_v2] 希望增加一个显示图片的窗体，方便跟识别后的文本进行人工校对 (Issue #2)




 
批量识别模式吗？

**Comment by hiroi-sora** [comment]
暂时实现了双击文件路径，用系统图片查看器打开该图片。

以后再写个更完善的内置图片预览窗口。
