### ISSUE TITLE
启动报python3.dll错误

### ISSUE THREAD

**Issue by StrollStars** [hiroi-sora/Umi-OCR_v2#21]
64位Win7，启动程序报如下错误：

```
> ---------------------------
ERROR
---------------------------
Cannot find Py_Main() in:

\Umi-OCR_Rapid_win7_dev_20230925\UmiOCR-data\.runtime\python3.dll
---------------------------
确定   
---------------------------
```

**Comment by hiroi-sora** [comment]
来到此路径：
`UmiOCR-data\.runtime`
按住Shift+右键 → ”在此处打开命令窗口“
输入：`python.exe`
回车。

如果输出了一堆python版本号等信息，最后一行是 `>>> _` ，说明py环境没有问题。
那么请在 `UmiOCR-data` 中新建一个 `启动.bat` ，输入这行命令：
`start "" .runtime/python.exe main.py`
双击  `启动.bat` ，看看能否启动Umi-OCR。

如果输入`python.exe`后无法启动py环境或者有报错，请重新下载解压Umi-OCR 。

**Comment by hiroi-sora** [comment]
我在一个早期win7 iso的虚拟机上重现了该错误。经过排查，发现是缺VC运行库的问题。

解决方法：

1. 下载安装VC运行库
https://aka.ms/vs/17/release/vc_redist.x64.exe

2. 尝试启动软件。如果显卡驱动正常，此时能正确打开软件并使用Rapid库进行离线OCR了。
3. 如果出现 `Umi-OCR.exe 已停止工作` 的弹窗，说明显卡驱动不全。（如果该系统之前没有VC运行库，大概率显卡驱动也是不全的。）那么请按照 [issue #22](https://github.com/hiroi-sora/Umi-OCR_v2/issues/22) 的方法，下载 [opengl32sw.zip](https://github.com/hiroi-sora/Umi-OCR_v2/files/12846485/opengl32sw.zip)，然后修改设置项为 AA_UseSoftwareOpenGL 。

经过上述操作，大概率可以让Umi跑起来了。

**Comment by StrollStars** [comment]
@hiroi-sora 安装了运行库（32位和6位都装了），还是报一样的错误。

**Comment by hiroi-sora** [comment]
去到 `UmiOCR-data\runtime` ，直接点击启动 `python.exe` ，看看有无异常？报什么错？

**Comment by hiroi-sora** [comment]
不可能和原有py冲突的，启动器根本不认识环境变量中的py，它只会试图调用Umi目录中自带的解释器。

如果你说直接点击运行 `UmiOCR-data\.runtime\python.exe` 完全正常，那这是个好消息。请尝试以下方法，跳过启动器，直接唤起解释器：

在目录 `UmiOCR-data` 中新建一个 `启动.bat` ，输入：
```
start "" .runtime/python.exe main.py
```
双击 `启动.bat` ，看看能否启动Umi-OCR。

**Comment by StrollStars** [comment]
@hiroi-sora CLI第一行显示`翻译未加载`，不过GUI启动了。
启动的GUI可以使用截图OCR，但是如果把该标签页关闭了，就无法再次打开，也就无法截图了，CLI中显示`WinError 31`和一串问号的错误。
重新运行`启动.bat`后可以再次使用，情况如上。

**Comment by hiroi-sora** [comment]
`翻译未加载` 是正常的，截图标签页无法再次开启就不正常。

可以的话，麻烦将遇到过的所有错误复制下来或者截图下来，发到这里，我会进一步调查。

系统详细信息也发一下，按win+r，输入`msinfo32` ，将窗口放到最大，截个图。

感谢协助！

另外，昨天发布的 [v1.3.7版](https://github.com/hiroi-sora/Umi-OCR/releases) 也支持win7了，你可以试试老版本在你的电脑上能否正常使用。

**Comment by StrollStars** [comment]
@hiroi-sora 
### [v1.3.7版](https://github.com/hiroi-sora/Umi-OCR/releases)
运行毫无问题。
### [预览版 dev 20231010](https://github.com/hiroi-sora/Umi-OCR_v2/releases/tag/dev%2F20231010)
#### 系统信息
![系统信息](https://github.com/hiroi-sora/Umi-OCR_v2/assets/10942225/ec70d834-49ec-423e-9e1f-939e0099e07e)
#### 命令行界面
![CLI](https://github.com/hiroi-sora/Umi-OCR_v2/assets/10942225/f1334951-07c2-48e2-a379-0fc8a2ee0f04)
##### 说明
1. 两个`ScreenshotOCR_1`之间是第一次打开`截图OCR`，没做任何操作后关闭标签页；
2. `ScreenshotOCR_2`到`%paste%`之间是第二次打开`截图OCR`，进行截图操作后关闭标签页；
3. `%paste%`之下是再次点击`截图OCR`，无法打开标签页了，但如果不做截图操作就没问题。
##### 其它问题
1. opengl32sw.dll是OpenGL相关，缺失没关系吧？
2. 是不是因为测试版所以会有CLI界面？
3. 为什么我CLI中每个汉字都会重复？

**Comment by hiroi-sora** [comment]
感谢你的测试。

- 关于系统信息：你的系统版本7601跟我的测试环境一样（即最后一个win7版本），所以应该不是主版本太旧导致的异常。我推测是有部分系统运行库错误导致。
如果你也是开发者，那么有一定可能，某些开发环境改写了系统运行库的优先级，让程序优先使用开发环境自带的库。而这些库恰好与 Umi v2 不兼容。

然后v2在你的电脑上主要存在2个问题：

1. 无法通过启动器`Umi-OCR.exe`启动，只能通过bat启动。（正常通过exe启动是不会有CLI的，用bat才会有CLI。）
2. 第二次截图操作会出现`WinError 31`的报错。

关于问题1，我暂时没有头绪，需要掌握更多信息才能判断。如果有别的用户有相同问题，请务必反馈，找找你们的共性。

关于问题2，确实有可能由`opengl32sw.dll`缺失引起。
- v2基于qt-qml，这是一种OpenGL渲染的UI框架，能制作复杂而高性能的UI。大部分系统都会自带`opengl32sw.dll`，我就没有将它放到发行包里。你可以[下载opengl32sw.zip](https://github.com/hiroi-sora/Umi-OCR_v2/files/12846485/opengl32sw.zip)，将dll放到该目录`UmiOCR-data/site-packages/PySide2/`
- 在截图界面，我使用了一些含特殊渲染效果的遮罩层。可能此时无法输出渲染特效而导致`WinError 31`。

关于补充：
- CLI汉字重复是win7 gbk编码导致的小问题，不会影响程序运行。
- v1只支持Paddle引擎，而v2你下载的是Rapid引擎版。如果v2也下载Paddle引擎，那么识别效果是一毛一样的。

**Comment by hiroi-sora** [comment]
Paddle和Rapid引擎在图像前处理阶段有一些差别，可能导致对同一张图片产生不同的识别效果。但总体而言差别不会很大。

是的，目前没有OCR库可以很好的实现混合多语言识别。最多做到英文+另1种语言。可见这里的讨论：

https://github.com/hiroi-sora/PaddleOCR-json/issues/75

**Comment by StrollStars** [comment]
@hiroi-sora 感谢帮我耐心测试，我先用其他版本好了。
如果是英文+另1种语言，那选择识别语言的时候是选择英文还是另1种语言？

**Comment by hiroi-sora** [comment]
不是，意思是大多数语言库（如简中，繁中，日文……）它们都自带英文识别。

不过，它们对长篇英文段落的识别效果，可能没有纯英文库好。

**Comment by StrollStars** [comment]
@hiroi-sora 那这么说来识别语言的时候是应该选择另一种语言了。
我发现对日文的识别，V2效果比V1要好，现在主要的两个问题：启动和连续识别，希望能够优先解决后面那个。

**Comment by hiroi-sora** [comment]
问题1有了初步的解决方案：强制启动，并隐藏控制台。
https://github.com/hiroi-sora/Umi-OCR/issues/208

问题2仍无解……

**Comment by hiroi-sora** [comment]
在 [之后的版本中](https://github.com/hiroi-sora/Umi-OCR_v2/releases) ，如果 `Umi-OCR.exe` 失效，可以用备用启动器：
```
UmiOCR-data/RUN_GUI.bat
```

它以最大兼容性启动软件，且不显示控制台窗口。

**Comment by StrollStars** [comment]
@hiroi-sora [预览版 dev 20231025](https://github.com/hiroi-sora/Umi-OCR_v2/releases/tag/dev%2F20231025)运行Umi-OCR.exe并连续截图没有问题，感谢开发者。
