### ISSUE TITLE
releases的预览版 dev 20231010下载报错404

### ISSUE THREAD

**Issue by finddream2023** [hiroi-sora/Umi-OCR_v2#23]
releases的预览版 dev 20231010下载报错404，无法下载，敬请修复

**Comment by hiroi-sora** [comment]
啊？我试了一下似乎没问题。你是不是没开科学上网？或者换个节点试试

**Comment by finddream2023** [comment]
> 啊？我试了一下似乎没问题。你是不是没开科学上网？或者换个节点试试

不好意思，开了个fastgithub的项目，居然会下载404，关掉就行了
