### ISSUE TITLE
截图隐藏窗体之后会增加吗？

### ISSUE THREAD

**Issue by zelohon** [hiroi-sora/Umi-OCR_v2#26]
截图隐藏窗体之后会增加吗？

**Comment by hiroi-sora** [comment]
问得好。很简单的小功能，之前纯粹是我忘记加了😂

**Comment by zelohon** [comment]
> 问得好。很简单的小功能，之前纯粹是我忘记加了 😂 已加上。

测试后的效果确实达到了  但是有一个问题就是  比如 打开主界面  点击截图按钮     这个时候 如果不去左键框选  直接点鼠标右键  主界面不会复原！    这样的话  还需要从右下任务栏里点出来主界面！

**Comment by zelohon** [comment]
完美！
