### ISSUE TITLE
设置无法保存？

### ISSUE THREAD

**Issue by Baiyssy** [hiroi-sora/Umi-OCR_v2#30]
我在全局设置里设置了关闭主窗口时退出应用，
关闭窗口，应用就退出了。
但是再打开，关闭窗口还是最小化到系统托盘。
我还试过用管理员权限运行，效果也一样。

**Comment by hiroi-sora** [comment]
感谢提醒，问题已修复。

你可以按下列步骤修复应用：
1. 用记事本打开 `UmiOCR-data\qt_res\qml\Configs\Configs.qml`
2. 复制这个链接的全文 https://github.com/hiroi-sora/Umi-OCR_v2/blob/main/UmiOCR-data/qt_res/qml/Configs/Configs.qml
3. 覆盖粘贴到记事本中，保存。

**Comment by Baiyssy** [comment]
谢谢！
不过操作的结果是这个设置固定在关闭主窗口时退出应用，不能改成关闭窗口最小化到系统托盘了。

**Comment by hiroi-sora** [comment]
啊，应该不会吧，我测试的结果是`退出应用`和`最小化到托盘`两个选项都可以被保存

**Comment by hiroi-sora** [comment]
哦，用管理员可以保存，用普通用户权限就不能保存设置吗？那确实有可能。你试试别的设置项，是不是也不能保存。然后将Umi-OCR换个路径试试。

**Comment by Baiyssy** [comment]
用绝对路径的文件搞定了，谢谢！

**Comment by bitjerry** [comment]
同样的问题, dev20231025. 这是一个权限问题, 当我用管理员修改设置才生效. 否则重启软件会又恢复了.
建议在无法写入配置时加一个提示弹窗, 请求提升权限, 这样程序比较健壮, 而不会令人困惑.

**Comment by hiroi-sora** [comment]
@bitjerry 

感谢建议，会考虑。
