### ISSUE TITLE
两个小建议！

### ISSUE THREAD

**Issue by zelohon** [hiroi-sora/Umi-OCR_v2#32]
1、识别记录建议添加复制选项 而不是鼠标右键复制！
2、鼠标框选识别文本信息时 如果鼠标像左侧移出文本记录识别框时候 会出现文本截断问题 无法全部选择！
![GIF](https://github.com/hiroi-sora/Umi-OCR_v2/assets/36800197/a46ea7a1-94f6-4b0f-af38-a6067300d2db)

**Comment by hiroi-sora** [comment]
已实现你的建议。

![GIF 2023-10-22 18-05-32](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/9fbdc5be-0c6e-4af1-a664-f84f25164ffb)

**Comment by zelohon** [comment]
完美！
