### ISSUE TITLE
建议：截图识别也可以到本地指定的文件txt

### ISSUE THREAD

**Issue by cukkk** [hiroi-sora/Umi-OCR_v2#34]
建议截图识别也可以保存结果到本地指定的文件

**Comment by hiroi-sora** [comment]
建议收到，之后会考虑

**Comment by hiroi-sora** [comment]
可以通过命令行指令 将截图结果输出到指定文件。见文档：
https://github.com/hiroi-sora/Umi-OCR/blob/main/docs/README_CLI.md#%E7%BB%93%E6%9E%9C%E8%BE%93%E5%87%BA
