### ISSUE TITLE
部署

### ISSUE THREAD

**Issue by liuqz90** [hiroi-sora/Umi-OCR_v2#35]
可以部署到Linux 作为一个服务吗

**Comment by hiroi-sora** [comment]
暂不支持

**Comment by liuqz90** [comment]
我找了个springboot的程序，但是没有这个能输出txt的，text的文本是您根据图片识别的坐标然后自己输出的吗？PaddleOCR-json这个文件夹里面的东西，是通过何种方式可以取得

**Comment by hiroi-sora** [comment]
https://github.com/hiroi-sora/PaddleOCR-json

**Comment by iszmxw** [comment]
> 可以部署到Linux 作为一个服务吗

可以支持 linux 的 #61
