### ISSUE TITLE
这个后缀的问题

### ISSUE THREAD

**Issue by lhj5426** [hiroi-sora/Umi-OCR_v2#36]
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/30548000/741466db-7453-4e41-8d8d-c9c28288b643)
诶 大佬 这个后缀的问题 现在是每次更新都有手动修改吗？ 
[ub.com](https://github.com/hiroi-sora/Umi-OCR_v2/issues/1)

今天更新了下 跑的时候发现又是文件名后缀。TXT了 哈哈

**Comment by hiroi-sora** [comment]
行了，我写入更新了。

麻烦再改这一次，下个版本就不用改了

**Comment by lhj5426** [comment]
> 行了，我写入更新了。
> 
> 麻烦再改这一次，下个版本就不用改了

非常感谢
