### ISSUE TITLE
最新版本截图报错

### ISSUE THREAD

**Issue by S091** [hiroi-sora/Umi-OCR_v2#37]
![6c3abd75e20988d020acade7e32b984](https://github.com/hiroi-sora/Umi-OCR_v2/assets/58965329/58f67df4-0238-473e-b26c-e959c6f8a22a)
win10

**Comment by S091** [comment]
更换rapid版本成功

**Comment by hiroi-sora** [comment]
嗯，可能是CPU不兼容paddle引擎。

如果可以的话试一下，Paddle版本双击打开
```
UmiOCR-data\plugins\win7_x64_PaddleOCR-json\PaddleOCR-json.exe
```
看看有什么报错。

**Comment by S091** [comment]
> 嗯，可能是CPU不兼容paddle引擎。
> 
> 如果可以的话试一下，Paddle版本双击打开
> 
> ```
> UmiOCR-data\plugins\win7_x64_PaddleOCR-json\PaddleOCR-json.exe
> ```
> 
> 看看有什么报错。

应用程序无法正常启动0xc000142

**Comment by hiroi-sora** [comment]
嗯，`0xc000142`大概率就是CPU缺乏AVX指令集而无法运行Paddle引擎了。请继续使用Rapid版本吧。
