### ISSUE TITLE
保存csv格式打开时文字乱码

### ISSUE THREAD

**Issue by Ao08** [hiroi-sora/Umi-OCR_v2#39]
也不知道是我本地环境还是什么问题 如图[https://s1.locimg.com/2023/10/30/0c578b868b9d4.jpg](url)

**Comment by hiroi-sora** [comment]
编码问题，Umi采用标准utf-8编码，微软Excel可能用的是本地编码或者带bom的utf-8编码。网上有很多解决方法。

或者先用WPS打开保存一下，WPS可以自动识别编码。
