### ISSUE TITLE
自动复制结果希望是排版后的结果.

### ISSUE THREAD

**Issue by cjdd2000** [hiroi-sora/Umi-OCR_v2#4]
和CopyTranslator联动的时候,识别的英文结果变成一行,非常影响阅读.
希望自动复制的结果是和软件上显示的是一样的.分行的

**Comment by cjdd2000** [comment]
![1](https://github.com/hiroi-sora/Umi-OCR_v2/assets/137271622/0b3d3be9-b6da-43c6-b7a9-dd9418cd29d0)

**Comment by hiroi-sora** [comment]
实际上，自动复制的结果应该与软件面板是一毛一样的。你可以退出CopyTranslator，只使用umi来测试一下。

CopyTranslator也有个排版功能，会自动去除剪贴板中文字的换行。这在阅读pdf时很有用，但有些时候会惹出麻烦。你检测一下是不是打开了这个开关。

**Comment by cjdd2000** [comment]
非常感谢,  其实之前在CopyTranslator上也早过相关设置...去掉上面的自动格式化选项....刚刚你说以后,我再次仔细核对.....发现去除换行的选项叫:自动净化.
(lll￢ω￢)

**Comment by cjdd2000** [comment]
已经解决...多谢大佬
