### ISSUE TITLE
需要部署在服务器的ocr服务端

### ISSUE THREAD

**Issue by xiaolang147258** [hiroi-sora/Umi-OCR_v2#45]
可否出一个可以部署在linux服务器的服务端版本，这样就不需要去买供应商的接口了

**Comment by xiaolang147258** [comment]
只需要提供上传图片的功能，服务端接口直接返回识别的图片文字即可

**Comment by hiroi-sora** [comment]
忙，暂无计划

**Comment by iszmxw** [comment]
可以先体验一下这个 #61

**Comment by mengdwwork** [comment]
> 可以先体验一下这个 #61

这个怎么搞？可以外网访问？

**Comment by iszmxw** [comment]
> > 可以先体验一下这个 #61
> 
> 这个怎么搞？可以外网访问？

可以的，我又优化了一下，封装了docker

**Comment by hiroi-sora** [comment]
最新版本，已支持原生Linux版本和Docker部署，见 [Docker部署文档](https://github.com/hiroi-sora/Umi-OCR_runtime_linux/blob/main/README-docker.md) 。
