### ISSUE TITLE
运行报错，提示找不到 No module named 'py_src.platform.win32'

### ISSUE THREAD

**Issue by skybc** [hiroi-sora/Umi-OCR_v2#46]
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/20303222/cc52bebc-bf77-45f0-b7ca-f7d8485763ae)

**Comment by skybc** [comment]
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/20303222/7c82a0ab-2647-4f93-887a-795e78f9314e)

**Comment by hiroi-sora** [comment]
请尝试在下述路径创建一个空文件 `__init__.py` 。
```
UmiOCR-data\py_src\platform\win32
```
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/b293d159-3f47-4203-8bcd-74df2de9c901)
