### ISSUE TITLE
批量识别导出CSV中文字符结果乱码

### ISSUE THREAD

**Issue by AlvinPPP** [hiroi-sora/Umi-OCR_v2#48]
我拿一组发票的图片做测试，输出CSV，查看表格时看到中文字符乱码；
将其直接改格式为txt另存为ANSI编码，再直接改为CSV后，然后中文字符显示正常。
是不是outputCsv的utf-8的影响？

**Comment by hiroi-sora** [comment]
是的，我输出是utf-8编码，而Excel默认使用本地编码，直接打开会乱码。如果WPS则能直接识别utf-8。

考虑之后改为适应系统本地编码。
