### ISSUE TITLE
http模式 上传base64文件大小问题

### ISSUE THREAD

**Issue by SuperMMORPG** [hiroi-sora/Umi-OCR_v2#49]
http服务 上传文件的时候，如果转过来的图片base64信息比较大。
web服务器会返回 413 Request Entity Too Large  问题。

**Comment by SuperMMORPG** [comment]
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 413 Request Entity Too Large</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 413 Request Entity Too Large</h1>
            <p>Sorry, the requested URL <tt>&#039;http://127.0.0.1:1224/api/ocr&#039;</tt>
               caused an error:</p>
            <pre>Request to large</pre>
        </body>
    </html>

**Comment by hiroi-sora** [comment]
确实，我没考虑到请求大小的问题。

你可以通过下述操作调整请求大小：

1. 打开文件
```
UmiOCR-data\py_src\server\web_server.py
```

2. 第115行左右，原本是：
```python
        UmiWeb.run(server=self._server)
```
将它改为：
```python
        UmiWeb.run(server=self._server, max_body_size=10 * 1024 * 1024)
```
这将设置单次请求上限为10MB。你可以改为别的值。

请测试该方法是否有效。

**Comment by SuperMMORPG** [comment]
设置后， 方法可行。   感谢！
