### ISSUE TITLE
能不能自己改ocr引擎？

### ISSUE THREAD

**Issue by ButterfliesGitHub** [hiroi-sora/Umi-OCR_v2#51]
![屏幕截图 2023-11-06 230108](https://github.com/hiroi-sora/Umi-OCR_v2/assets/25365693/63bbf35d-439f-4512-93d8-5298bee9e6be)
请问能不能自己改ocr引擎的？

**Comment by hiroi-sora** [comment]
当然。

- 想导入已有的引擎插件：[插件库](https://github.com/hiroi-sora/Umi-OCR_plugins)
- 想自己开发引擎插件或使用在线接口：见 [插件开发文档](https://github.com/hiroi-sora/Umi-OCR_plugins/tree/main/demo_AbaOCR) 。
