### ISSUE TITLE
有没有什么模型可以将ppt中散落的文本框，分割出文本框段落？

### ISSUE THREAD

**Issue by nissansz** [hiroi-sora/Umi-OCR_v2#56]
有没有什么模型可以将ppt中散落的文本框，分割出文本框段落？

**Comment by hiroi-sora** [comment]
来个例图

**Comment by nissansz** [comment]
![药理学(沈祥春,陈晓红)PPT模板_Page_63](https://github.com/hiroi-sora/Umi-OCR_v2/assets/41010669/8a883a9f-c77a-4478-b711-f349d26010e8)
可能会有各种复杂的文本框，彼此靠近的，上下交错之类

**Comment by nissansz** [comment]
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/41010669/44993c24-15ec-418a-8287-5259bda20c85)

怎么切出单个文本框

**Comment by hiroi-sora** [comment]
使用段落合并中的 `多行-自然段`，可以尽量以文本框为单位进行划分。（但是，文本框之间的顺序，仍需你手动排序。）

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/120a71ae-a7dd-4262-b100-6441a7a34370)
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/30678727-c52a-4c71-acbc-442459091c60)

另，建议按照修改一个文件以提高准确度。
`UmiOCR-data/py_src/ocr/tbpu/merge_para.py`
 [参考这个commit](https://github.com/hiroi-sora/Umi-OCR_v2/commit/f4b96e8e48d283f2c6647221bcd680a3fae9d1af)，修改其中一行代码

**Comment by nissansz** [comment]
https://github.com/YCG09/chinese_ocr

这里的模型能转成onnx吗？
win10下怎么用DenseNet训练？

**Comment by hiroi-sora** [comment]
这个项目我不太了解，估计可能不行吧
