### ISSUE TITLE
譬如这种排版的如何识别？

### ISSUE THREAD

**Issue by 3815445** [hiroi-sora/Umi-OCR_v2#57]
![2023-11-12_200727](https://github.com/hiroi-sora/Umi-OCR_v2/assets/150584521/e4c811b3-599b-4a7e-b3bd-66476a3a9beb)
![2023-11-12_200532](https://github.com/hiroi-sora/Umi-OCR_v2/assets/150584521/960e1116-f5ac-4e65-ad42-5631c0c0bec6)

**Comment by hiroi-sora** [comment]
你的图没有上传成功哦

**Comment by 3815445** [comment]
补充图片了。谢谢！

**Comment by hiroi-sora** [comment]
针对这种双栏文档的排版模块正在开发，将在后续跟pdf识别一起推出。估计约在12月份。

**Comment by 3815445** [comment]
衷心感谢！期待！爬码不容易，辛苦了！

**Comment by hiroi-sora** [comment]
正式版 v2.1.0 起已支持对识别双栏布局的图片/PDF文档。
