### ISSUE TITLE
2.0新UI界面GPU占用率好高，还望大佬能优化一下 QAQ

### ISSUE THREAD

**Issue by MisakaNo23300** [hiroi-sora/Umi-OCR_v2#59]
![屏幕截图 2023-11-14 113045——v2 0](https://github.com/hiroi-sora/Umi-OCR_v2/assets/89892822/4d04b604-104d-49b7-9990-93bd8fc2058a)
![屏幕截图 2023-11-14 113248——v1 3 7](https://github.com/hiroi-sora/Umi-OCR_v2/assets/89892822/5a18ab86-425e-4ac6-9a51-fd0a7b078bd2)

虽然占用率高，但是真的好用！

**Comment by hiroi-sora** [comment]
占有率高应该是不同显卡驱动的个别现象，qml框架本身性能优化很不错的。

你可以尝试：全局设置→勾选高级→渲染器，切换不同渲染器。

默认的`OpenGL ES`是用旧版api模拟，性能略差，显卡兼容性最好。

`Desktop OpenGL`则是用新版api，性能最佳，兼容性略差（不过对于你的amd核显应该没问题）。

还有cpu软渲染可以选择，通常cpu占用也不会太高。

试试吧~
