### ISSUE TITLE
【功能】自动复制

### ISSUE THREAD

**Issue by komiblog** [hiroi-sora/Umi-OCR_v2#64]
希望设置增加一个开关，用于控制截图OCR识别后，是否将结果自动复制到剪贴板

**Comment by hiroi-sora** [comment]
这个开关有的哦
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/b5da1c42-86bd-49f8-ab09-e3fb4756c90d)

**Comment by komiblog** [comment]
不好意思，只看了全局设置，原来在这啊😂。多谢答复！

**Comment by komiblog** [comment]
问题已解决
