### ISSUE TITLE
你好， 所有车辆行驶证图片均无法识别

### ISSUE THREAD

**Issue by 954224685** [hiroi-sora/Umi-OCR_v2#67]
你好，原因是，行驶证里面的0中间包含一个斜杠，参考图示

请问是否有解决办法，比如说可以增加这个比对的资源文件之类的？
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/112752918/14c15c95-fee0-4286-86c5-4ba38629708f)

测试了一下，整个软件做的非常棒，但是车辆行驶证，目前100%识别错误，100%是0这个引起的（参考上面图示），是否有解决方案建议？谢谢

**Comment by hiroi-sora** [comment]
https://github.com/hiroi-sora/Umi-OCR/issues/318
