### ISSUE TITLE
截图时显示器会闪烁一下

### ISSUE THREAD

**Issue by pheotry** [hiroi-sora/Umi-OCR_v2#7]
笔记本连接的显示器，显示器作为主屏幕，笔记本屏幕作为副屏。
显示器会闪烁一下，笔记本屏幕没有闪烁。

另外希望截图时的背景不要那么暗，稍微调高一点背景遮罩的亮度，可以和截图区域做出明显区分即可。

还有一个是启动的时候程序界面会卡死一下，显示未响应。

OS：22631.2361 win11 pro beta
软件版本2.0.0-dev.20230925

**Comment by hiroi-sora** [comment]
>  显示器闪烁

请在全局设置里，将渲染器改为`OpenGL ES`。一般这样就能消除闪烁现象。
如果还不行，就改为`关闭硬件加速`。
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/81c5affe-8b1c-4107-9ed2-cf7f6c8e2272)

-----

> 截图时的背景不要那么暗

你可以修改如下文件：

`UmiOCR-data\res\qml\TabPages\ScreenshotOCR\ScreenshotWindowComp.qml`

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/fdfc02fb-8586-4efd-8740-4e085e671c6a)

找到 `color: "#88000000"` 这一行，将**前两个数字**改为小一点的值，如 `color: "#44000000"` 。
如果你改到某个值，觉得很舒适，请告诉我~

-----

> 启动卡死现象

程序启动步骤确实存在可以优化的地方，我会再调查一下。

**Comment by pheotry** [comment]
改为OpenGL ES不闪烁了。

试了下color: "#73000000"，感觉还可以

**Comment by hiroi-sora** [comment]
好滴。顺便问下，你是N卡吧？似乎N卡更容易出现闪烁的这个问题

**Comment by FallingSakura** [comment]
> 好滴。顺便问下，你是N卡吧？似乎N卡更容易出现闪烁的这个问题

我是 N 卡，也遇到了类似的情况，改为 OpenGL ES 后就可以正常用了。

**Comment by pheotry** [comment]
> > 好滴。顺便问下，你是N卡吧？似乎N卡更容易出现闪烁的这个问题
> 
> 我是 N 卡，也遇到了类似的情况，改为 OpenGL ES 后就可以正常用了。

是N卡
