### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by FallingSakura** [hiroi-sora/Umi-OCR_v2#8]
用的是最新预览版 v2.0.0-dev，效果如下：

![](https://cdn.jsdelivr.net/gh/FallingSakura/Source@main/img/202309290658423.webp)

- 屏占比可以优化一下。目前缩放到最小的话占用屏幕约八分之一面积，UI 的图标显示比例太大了，主要功能就两个可以做成快捷键，然后添加一个修改显示比例的设置，最好搞个无边框。

*体验还是很棒的。*

**Comment by hiroi-sora** [comment]
建议收到~ 感谢反馈

**Comment by pheotry** [comment]
> 建议收到~ 感谢反馈

还像v1一样放到上面，这样图标看着也和右边的设置和记录UI更加一致。
还有就是最上面这部分阴影显得很怪
![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/43376740/8385ebc6-4053-43c4-9dfa-04c13b9a28b5)
